version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: age-of-war-app
    volumes:
      - ./../:/home/app
    command: sleep infinity